### ISSUE TITLE
col-0 & equalHeight Issue

### ISSUE THREAD

**Issue by TheKidCoder** [devlint/gridlex#27]
If you were to have a grid as follows:
```html
<div class="grid-equalHeight">
  <div class="col></div>
  <div class="col-2_sm-0_md-0"></div>
</div>
```

The resulting cascade is: https://cl.ly/3g2m093r1p2l

As you can see, the application of equalHeight is overriding the `display: none`.

**Comment by bryanwillis** [comment]
@TheKidCoder Seems like there's a few issues with `.equalHeight`. 

Have you noticed yet that while `.equalHeight` causes the block element children of `.col-*` grow vertically, they end up shrinking horizontally as though they were inline blocks.


http://codepen.io/bootstrapped/pen/bwKoBA?editors=1100

Basically the only way for it to work is the children elements need to be wrapped in a div that has either `width:100%;` or `flex-grow: 1;` applied to it otherwise they will shrink horizontally and act as inline-blocks even if they're not.


**Temp solutions:**


```html
<style>
.block {
  width: 100%;
}
</style>
  <div class="col-6_sm-12">
    <div class="block">
      
    </div>
  </div>
```

**or**

```html
<style>
.block {
  flex-grow: 1;
}
</style>
  <div class="col-6_sm-12">
    <div class="block">
      
    </div>
  </div>
```

**Comment by bryanwillis** [comment]
Actually, .equalHeight seems pointless the more I look at it.  Since width: 100%f needs to be added added to the child element of the columns, you could actually just add height: 100% to that element and drop .equalHeight all together.

So from what I can tell this actually does the same thing with needing .equalHeight:

```html
<style>
.h100 {
  height: 100%;
}
</style>
<div class="grid">
  <div class="col-6_sm-12">
    <div class="block">
    ....
    </div>
  <div class="col-6_sm-12">
    <div class="h100">
    ....
    </div>
  </div>
```

I realized the horizontal shrinking issue could be fixed by adding `flex-direcion: column` to the .col classes, but that messes other things up, like when using `.grid col` with nested columns. 

Anyway, maybe someone else has a better solutions, but for now the .equalHeight doesn't seem worth it to me.

**Comment by devlint** [comment]
Hello both of you, 
@TheKidCoder I've merged your code.
@bryanwillis I fix your issue by addind children of equalHeight>cols `flex: 1` value.
