### ISSUE TITLE
equalHeight not working in Safari Mac

### ISSUE THREAD

**Issue by maxleistner** [devlint/gridlex#34]
If i use the class `.grid-equalHeight` it is working fine in Chrome, but not in Safari for Mac. Any ideas how to work this out? Any fixes planing?

![Screenshot](https://cloud.githubusercontent.com/assets/7567185/19767044/3d2ea1f4-9c51-11e6-819a-b281425b05b4.png)

**Comment by programmiri** [comment]
This specific problem's presumably caused by a nested div:

```
<div class="grid-equalHeight">
  <div class="col">
    <div class="some-element">
      <div class="some-content">
      </div>
    </div>
  </div>
 <div class="col">
    <div class="some-element">
      <div class="some-content">
      </div>
    </div>
  </div>
</div>
```

giving the "some-element" class the properties `display: flex` and `flex-direction: column` and the "some-conten" class the property `flex:1` fixed the problem in this specific setting. 

Helpful sources I read about the topic:
https://stackoverflow.com/questions/33481669/equal-height-nested-divs-in-bootstrap 
https://stackoverflow.com/questions/33636796/chrome-safari-not-filling-100-height-of-flex-parent

**Comment by devlint** [comment]
Thanx @programmiri for your reply :)
